version: build-{branch}-#{build}

branches:
  only:
  - cml2

image:
- Visual Studio 2017

environment:
  matrix:
    - GENERATOR: "Visual Studio 12 2013 Win64"
      CONFIG: Release
      BOOST_ROOT: "C:\\Libraries\\boost_1_64_0"

    - GENERATOR: "Visual Studio 14 2015 Win64"
      CONFIG: Release
      BOOST_ROOT: "C:\\Libraries\\boost_1_64_0"

    - GENERATOR: "Visual Studio 15 2017 Win64"
      CONFIG: Release
      BOOST_ROOT: "C:\\Libraries\\boost_1_64_0"

build_script:
  - mkdir build
  - cd build
  - cmake "-G%GENERATOR%" -DBOOST_ROOT="%BOOST_ROOT%" -DCML_BUILD_TESTING=ON ..
  - cmake --build . --config "%CONFIG%"

test_script:
  - ctest -V --build-config "%CONFIG%"
