language: cpp

addons:
  apt:
    sources: &apt_sources
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty
      - llvm-toolchain-trusty-4.0

matrix:
  fast_finish: true
  include:

#     - os: osx
#       osx_image: xcode7.3
#       env:
#         - BOOST_ROOT="BOOST_ROOT=/usr/local"
# 
#     - os: osx
#       osx_image: xcode8.3
#       env:
#         - BOOST_ROOT="BOOST_ROOT=/usr/local"

    - os: linux
      dist: trusty
      addons: &clang40
        apt:
          packages: ['libboost-test-dev', 'clang-4.0']
          sources: *apt_sources
      env:
        - MATRIX_EVAL="CC=clang-4.0 && CXX=clang++-4.0"
        - BOOST_ROOT="BOOST_ROOT=/usr"

#     - os: linux
#       dist: trusty
#       addons: &clang50
#         apt:
#           packages: ['libboost-test-dev', 'clang-5.0']
#           sources: *apt_sources
#       env:
#         - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"
#         - BOOST_ROOT="BOOST_ROOT=/usr"


before_install:
  - if [ ${TRAVIS_OS_NAME} == "osx" ]; then
      brew update;
      brew outdated boost || brew upgrade boost;
      brew outdated cmake || brew upgrade cmake;
    fi

  - if [ ${TRAVIS_OS_NAME} == "linux" ]; then
      eval "${MATRIX_EVAL}";
    fi

  - eval "${BOOST_ROOT}"

before_script:
  - mkdir build 
  - cd build

script:
  - ${CXX} --version
  - cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=RELEASE -DBOOST_ROOT=${BOOST_ROOT} -DCML_BUILD_TESTING:Bool=ON ..
  - cmake --build . --config Release
  - ctest -C Release
