language: cpp

matrix:
  fast_finish: true
  include:

    - os: osx
      osx_image: xcode7.3

    - os: osx
      osx_image: xcode8.3

before_install:
  - if [ ${TRAVIS_OS_NAME} == "osx" ]; then
      brew update;
      brew outdated boost || brew upgrade boost;
      brew outdated cmake || brew upgrade cmake;
    fi

before_script:
  - mkdir build 
  - cd build

script:
  - cmake -G "Unix Makefiles" -DBOOST_ROOT=/usr/local -DCML_BUILD_TESTING:Bool=ON ..
  - cmake --build . --config Release
  - ctest -C Release
